#!/bin/bash
. "$GIT_DIR/hooks/change_detector.sh"
. "$GIT_DIR/hooks/cssbuilder/compile-sass.sh"

if has_changed post-merge \
	web/assets/*/*/*.scss \
	web/assets/*/*.scss \
	web/assets/*.scss
then
	compileSass
fi
